language: java
dist: trusty
sudo: required

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "mks-security"
    token:
      secure: $SONAR_TOKEN # Set in the settings page of your repository, as a secure variable

jdk:
  - openjdk11

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'